Repository planetarium/NineChronicles.IAP, pull requests merged in 2023-11, with the labels that each got.

#93 Manual unload function
  worker/.gitignore
  worker/worker/manual.py
  worker/worker/unload_data.json.example
  worker/worker_cdk_stack.py
Labels: enhancement, Small

#91 handle UnloadFromMyGarages recipient address by PlanetID
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  .github/workflows/test.yml
  common/_graphql.py
  common/models/product.py
  common/utils/address.py
  iap/api/purchase.py
  tests/utils/address_test.py
  worker/worker/handler.py
Labels: Medium

#95 Prepare multiplanet internal test
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  .github/workflows/test.yml
  common/_graphql.py
  common/alembic/versions/4beb3c9fcd4b_set_non_nullable_columns.py
  common/alembic/versions/b7a685e5ef1c_add_planet_id.py
  common/models/product.py
  common/models/receipt.py
  common/utils/address.py
  common/utils/receipt.py
  iap/api/purchase.py
  iap/frontend/src/routes/receipt/+page.svelte
  iap/schemas/receipt.py
  tests/utils/address_test.py
  worker/.gitignore
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/unload_data.json.example
  worker/worker_cdk_stack.py
Labels: Large

#96 Communicate with SeasonPass API when buy season pass premium
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/alembic/versions/e75f93e4cc06_add_message_column_to_receipt.py
  common/models/receipt.py
  common/shared_stack.py
  iap/api/product.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/settings/__init__.py
  iap/utils.py
  worker/worker_cdk_stack.py
Labels: enhancement, Medium

#97 Upgrade seasonpass
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/alembic/versions/e75f93e4cc06_add_message_column_to_receipt.py
  common/models/receipt.py
  common/shared_stack.py
  iap/api/product.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/settings/__init__.py
  iap/utils.py
  worker/worker_cdk_stack.py
Labels: enhancement

#99 Function does not accept filter_by. Use filter
  iap/utils.py
Labels: bug, Extra Small

#98 Set all addresses to lower case
  iap/api/product.py
  iap/api/purchase.py
Labels: bug, Extra Small

#100 Remove non-existing function
  worker/worker/handler.py
Labels: bug, Extra Small

#101 0.5.2
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  .github/workflows/test.yml
  CHANGELOG.md
  common/__init__.py
  common/_graphql.py
  common/alembic/versions/4beb3c9fcd4b_set_non_nullable_columns.py
  common/alembic/versions/b7a685e5ef1c_add_planet_id.py
  common/alembic/versions/e75f93e4cc06_add_message_column_to_receipt.py
  common/models/product.py
  common/models/receipt.py
  common/shared_stack.py
  common/utils/address.py
  common/utils/receipt.py
  iap/api/product.py
  iap/api/purchase.py
  iap/frontend/src/routes/receipt/+page.svelte
  iap/iap_cdk_stack.py
  iap/schemas/receipt.py
  iap/settings/__init__.py
  iap/utils.py
  pyproject.toml
  tests/utils/address_test.py
  worker/.gitignore
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/tracker.py
  worker/worker/unload_data.json.example
  worker/worker_cdk_stack.py
Labels: Extra Large, release

#102 Backmerge 0.5.2 to development
  CHANGELOG.md
  pyproject.toml
  worker/worker/golden_dust_by_ncg.py
  worker/worker/tracker.py
Labels: Extra Small, merge

#103 Pull development to 0.6.0
  CHANGELOG.md
  pyproject.toml
  worker/worker/golden_dust_by_ncg.py
  worker/worker/tracker.py
Labels: Extra Small, merge

#104 Add custom domain: api.9c.gg
  iap/iap_cdk_stack.py
Labels: enhancement

#106 Update multiplanetary appicances
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/_crypto.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/schemas/receipt.py
  worker/worker/handler.py
  worker/worker_cdk_stack.py
Labels: bug, enhancement

#107 Consider planet_id when checking purchase_limit
  iap/api/product.py
  iap/utils.py
Labels: bug

#108 Send product SKU into memo
  worker/worker/handler.py
Labels: enhancement

#109 Fix wrong import
  iap/api/product.py
Labels: bug

#110 Apply multiplanetary
  common/_graphql.py
  iap/api/product.py
  iap/api/purchase.py
  iap/utils.py
  worker/worker/manual.py
  worker/worker/tracker.py
Labels: enhancement

#111 Multiplanetary failover
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/_graphql.py
  iap/api/product.py
  iap/iap_cdk_stack.py
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/tracker.py
  worker/worker_cdk_stack.py
Labels: enhancement, Medium

#112 Add root package name
  worker/worker/manual.py
Labels: bug

#113 Memo in bridge must include recipient address
  worker/worker/handler.py
Labels: bug, Extra Small

#114 Bugfix/multiplanetary
  common/utils/receipt.py
  iap/api/purchase.py
  worker/worker/handler.py
Labels: bug, Extra Small

#115 Fix wrong season-pass upgrade API data
  iap/api/purchase.py
Labels: bug, Extra Small

#118 Feature/claim seasonpass items
  common/alembic/versions/73e03cbf8ba2_update_fungible_asset_product_to_use_.py
  common/consts.py
  common/models/product.py
  iap/api/product.py
  iap/api/purchase.py
  iap/schemas/product.py
Labels: enhancement, Small

#119 Handle item ID for season pass
  iap/api/purchase.py
  iap/schemas/product.py
Labels: bug, Extra Small

#120 Fix product time limit issue
  common/alembic/versions/32e8805e8364_add_time_limit_receipt_status.py
  common/enums.py
  iap/api/product.py
  iap/api/purchase.py
Labels: bug

#117 Feature/multiplanetary
  common/utils/garage.py
  worker/worker/tracker.py
Labels: enhancement, help wanted, Extra Small

#122 0.6.0
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  CHANGELOG.md
  common/__init__.py
  common/_crypto.py
  common/_graphql.py
  common/alembic/versions/32e8805e8364_add_time_limit_receipt_status.py
  common/alembic/versions/73e03cbf8ba2_update_fungible_asset_product_to_use_.py
  common/consts.py
  common/enums.py
  common/models/product.py
  common/shared_stack.py
  common/utils/garage.py
  common/utils/receipt.py
  iap/api/product.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/main.py
  iap/schemas/product.py
  iap/schemas/receipt.py
  iap/utils.py
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/tracker.py
  worker/worker_cdk_stack.py
Labels: Extra Large, release

#123 Backmerge 0.6.0 to dev
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/_crypto.py
  common/_graphql.py
  common/alembic/versions/32e8805e8364_add_time_limit_receipt_status.py
  common/alembic/versions/73e03cbf8ba2_update_fungible_asset_product_to_use_.py
  common/consts.py
  common/enums.py
  common/models/product.py
  common/shared_stack.py
  common/utils/garage.py
  common/utils/receipt.py
  iap/api/product.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/main.py
  iap/schemas/product.py
  iap/schemas/receipt.py
  iap/utils.py
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/tracker.py
  worker/worker_cdk_stack.py
Labels: Extra Large, merge

#127 Feature/revive tx tracker
  worker/worker/tracker.py
  worker/worker_cdk_stack.py
Labels: enhancement, Extra Small

#128 Enable APIGateway logging and X-Ray
  iap/iap_cdk_stack.py
Labels: Extra Small

#129 fix: remove full_log_format
  iap/iap_cdk_stack.py
Labels: Extra Small

#130 fix: change data_trace_enabled attr name
  iap/iap_cdk_stack.py
Labels: Extra Small

#131 fix: remove unnecessary log_group
  iap/iap_cdk_stack.py
Labels: Extra Small

#125 Update receipt table to manage tx and track heimdall
  common/alembic/versions/57e65ed34bd6_update_db_schema_to_manage_tx_data.py
  common/models/receipt.py
Labels: enhancement, Extra Small

#133 Fix wrong statement
  worker/worker/tracker.py
Labels: bug, Extra Small

#134 Faster receipt handling
  common/shared_stack.py
  worker/worker_cdk_stack.py
Labels: enhancement, Extra Small

#135 Fix purchase limit calculating logic
  iap/api/product.py
  iap/api/purchase.py
  iap/utils.py
Labels: bug

#137 Fix purchase limit calculating logic
  iap/api/product.py
  iap/api/purchase.py
  iap/utils.py
Labels: bug, Extra Small

#132 ✨ introduce: create unsigned tx
  .gitignore
  common/utils/transaction.py
  poetry.lock
  pyproject.toml
  tests/utils/test_transaction.py
Labels: Medium

#140 ✨ introduce: create action plain value
  common/lib9c/currency.py
  common/lib9c/fungible_asset.py
  common/utils/actions.py
  tests/lib9c/test_currency.py
  tests/lib9c/test_fungible_asset.py
  tests/utils/test_actions.py
Labels: Medium

#141 Save tx data
  worker/worker/handler.py
Labels: Extra Small

#142 Commit receipt instead flush
  iap/api/purchase.py
Labels: Extra Small

#143 🔧 refactor: create unsigned tx itself
  common/utils/actions.py
  common/utils/transaction.py
  tests/utils/test_actions.py
  tests/utils/test_transaction.py
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker/manual.py
Labels: Small

#145 Avoid TypeError when init sqs message
  worker/worker/handler.py
Labels: Extra Small

#144 Enqueue IAP SQS event except SeasonPass product
  iap/api/purchase.py
Labels: bug, Extra Small

#146 Avoid KeyError in planet_dict
  worker/worker/handler.py
Labels: Extra Small

#147 Avoid action id set
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker/manual.py
Labels: Extra Small

#148 Fix planet id for unsigned tx genesis
  worker/worker/handler.py
Labels: Extra Small

#150 log: add logging for worker
  worker/worker/handler.py
Labels: Extra Small

#149 Bugfix/misc
  common/utils/actions.py
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker/manual.py
Labels: bug, Extra Small

#153 fix: reference first
  worker/worker/handler.py
Labels: Extra Small

#154 🔧 impl: receipt.__dict__
  common/models/receipt.py
Labels: Extra Small

#155 fix: wrong serialize
  common/models/receipt.py
  worker/worker/handler.py
Labels: Extra Small

#158 fix: do not multiple line
  worker/worker/handler.py
Labels: Extra Small

#159 Feature/retreat receipt
  iap/schemas/receipt.py
Labels: enhancement

#161 Get receipt only from order data
  iap/schemas/receipt.py
Labels: enhancement

#163 Update retreat logic
  iap/api/purchase.py
  iap/schemas/receipt.py
Labels: bug

#164 Fix import path
  iap/api/purchase.py
Labels: bug

#165 fix: use context manager instead of try-catch
  worker/worker/handler.py
Labels: enhancement, Extra Small

#167 Select internal planet if not in mainnet
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
Labels: bug, Extra Small

#168 enable SQS message logging
  worker/worker/handler.py
Labels: Extra Small

#169 fix: do not ignore exception
  worker/worker/handler.py
Labels: Extra Small

#170 Release/0.7.0
  .gitignore
  common/_graphql.py
  common/alembic/versions/57e65ed34bd6_update_db_schema_to_manage_tx_data.py
  common/lib9c/currency.py
  common/lib9c/fungible_asset.py
  common/models/receipt.py
  common/shared_stack.py
  common/utils/actions.py
  common/utils/transaction.py
  iap/api/product.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/schemas/receipt.py
  iap/utils.py
  poetry.lock
  pyproject.toml
  tests/lib9c/test_currency.py
  tests/lib9c/test_fungible_asset.py
  tests/utils/test_actions.py
  tests/utils/test_transaction.py
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/tracker.py
  worker/worker_cdk_stack.py
Labels: Extra Large, release

#171 Backmerge Release/0.7.0 to development
  common/_graphql.py
  common/alembic/versions/57e65ed34bd6_update_db_schema_to_manage_tx_data.py
  common/models/receipt.py
  common/shared_stack.py
  common/utils/actions.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/schemas/receipt.py
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker/manual.py
  worker/worker/tracker.py
  worker/worker_cdk_stack.py
Labels: Medium, merge

#174 Fix wrong decimal places string
  common/lib9c/currency.py
Labels: bug, Extra Small

#173 Add internal headless addresses
  worker/worker/handler.py
Labels: bug, Extra Small

#175 Apply decimalPlacecs when creating Tx
  common/lib9c/fungible_asset.py
  common/models/product.py
  common/utils/actions.py
  tests/lib9c/test_fungible_asset.py
  tests/utils/test_actions.py
Labels: bug, Extra Small

#176 Release/0.7.1
  common/consts.py
  common/lib9c/currency.py
  common/lib9c/fungible_asset.py
  common/models/product.py
  common/utils/actions.py
  tests/lib9c/test_fungible_asset.py
  tests/utils/test_actions.py
  worker/worker/handler.py
Labels: Extra Small, release

#177 Backmerge 0.7.1 to development
  common/consts.py
  common/lib9c/currency.py
  common/lib9c/fungible_asset.py
  common/models/product.py
  common/utils/actions.py
  tests/lib9c/test_fungible_asset.py
  tests/utils/test_actions.py
  worker/worker/handler.py
Labels: Extra Small, merge
