Repository planetarium/NineChronicles.IAP, pull requests merged in 2023-10, with the labels that each got.

#77 0.4.0
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/alembic/versions/3c96c08258a1_update_product_model.py
  common/alembic/versions/74f4b954bd1b_update_product_model_add_l10n.py
  common/alembic/versions/d09361e553f0_update_product_model_add_paths.py
  common/enums.py
  common/models/l10n.py
  common/models/product.py
  common/poetry.lock
  common/utils/garage.py
  iap/api/__init__.py
  iap/api/l10n.py
  iap/api/product.py
  iap/iap_cdk_stack.py
  iap/main.py
  iap/schemas/box.py
  iap/schemas/item.py
  iap/schemas/l10n.py
  iap/schemas/product.py
  iap/schemas/receipt.py
  iap/utils.py
  poetry.lock
  pyproject.toml
  tests/__init__.py
  tests/conftest.py
  tests/test_image_link.py
  worker/worker/golden_dust_by_ncg.py
  worker/worker/handler.py
  worker/worker_cdk_stack.py
Labels: merge

#78 Validate apple IAP receipt
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/shared_stack.py
  common/utils/apple.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/schemas/product.py
  iap/schemas/receipt.py
  iap/settings/__init__.py
  iap/validator/common.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#79 Optimize Lambda layer
  .github/workflows/deploy.yml
  .github/workflows/synth.yml
  common/__init__.py
  common/pyproject.toml
  common/shared_stack.py
  iap/__init__.py
  iap/iap_cdk_stack.py
  poetry.lock
  pyproject.toml
  worker/worker_cdk_stack.py
Labels: enhancement

#80 Bugfix
  common/utils/garage.py
  iap/api/purchase.py
Labels: bug

#81 Add tags to stack
  app.py
Labels: enhancement

#82 Add tgas to AWS resources
  app.py
Labels: enhancement

#83 Update apple receipt data handling
  iap/api/purchase.py
  iap/schemas/receipt.py
  iap/validator/common.py
Labels: enhancement

#84 Release/0.5.0
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  .github/workflows/synth.yml
  app.py
  common/__init__.py
  common/pyproject.toml
  common/shared_stack.py
  common/utils/apple.py
  common/utils/garage.py
  iap/__init__.py
  iap/api/purchase.py
  iap/iap_cdk_stack.py
  iap/schemas/product.py
  iap/schemas/receipt.py
  iap/settings/__init__.py
  iap/validator/common.py
  poetry.lock
  pyproject.toml
  worker/worker_cdk_stack.py
Labels: release

#85 Extend SQS message visibility to lambda execution limit
  common/shared_stack.py
Labels: bug, release

#86 Backmerge Release/0.5.0
  common/shared_stack.py
  iap/api/purchase.py
  iap/schemas/receipt.py
  iap/validator/common.py
  pyproject.toml
  worker/worker/handler.py
  worker/worker_cdk_stack.py
Labels: merge

#87 Comment out productId comparison with nullable field
  iap/api/purchase.py
Labels: bug

#90 Handle if no product found
  common/alembic/versions/4beb3c9fcd4b_set_non_nullable_columns.py
  common/models/product.py
  iap/frontend/src/routes/receipt/+page.svelte
  iap/schemas/receipt.py
Labels: bug, Small

#89 Add planet_id on receipt
  common/alembic/versions/b7a685e5ef1c_add_planet_id.py
  common/models/receipt.py
  common/utils/receipt.py
  iap/api/purchase.py
  iap/schemas/receipt.py
Labels: Extra Small
